services:
  # app:
  #   container_name: chat-repo
  #   image: ${DEV:+ghcr.io/uithub/chat-repo:dev}
  #   build: ${DEV:+.}
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql
    restart: always

  cache:
    image: redis:7-alpine
    environment:
      - "REDIS_ARGS=--appendonly yes"
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - cache-data:/data
    restart: always

volumes:
  db-data:
  cache-data:
